version: '2'
services:
    wacdoc:
        build: .
        volumes:
          # FOR DEV PURPOSE ONLY - Disable in production
          # - $WACDOC_SRC:/src
          # FOR PROD
          - $UPLOAD_VOL:/src/uploads
        environment:
          - VIRTUAL_HOST=$WACDOC_HOST
          - VIRTUAL_PORT=3000
          - UID=$UID
          - GID=$GID
          - MASTERKEY=$MASTERKEY
    reverse-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
          - $HTTP_PORT:80/tcp
          - $HTTPS_PORT:443/tcp
        volumes:
          - $DOCKER_SOCK:/tmp/docker.sock:ro
          - ./files/proxy.conf:/etc/nginx/conf.d/my_proxy.conf